# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: forch/proto/acl_rules.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='forch/proto/acl_rules.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1b\x66orch/proto/acl_rules.proto\"#\n\x08\x41\x63lRules\x12\x17\n\x05rules\x18\x01 \x03(\x0b\x32\x08.AclRule\"W\n\x07\x41\x63lRule\x12\x0f\n\x07src_mac\x18\x01 \x01(\t\x12\x0f\n\x07\x64st_mac\x18\x02 \x01(\t\x12\x11\n\tfilter_id\x18\x03 \x01(\x05\x12\x17\n\x06\x61\x63tion\x18\x04 \x01(\x0e\x32\x07.Action\"\xac\x01\n\rTrafficFilter\x12\x11\n\tfilter_id\x18\x01 \x01(\x05\x12\x10\n\x08\x65th_type\x18\x02 \x01(\x0c\x12\x0f\n\x07\x65th_src\x18\x03 \x01(\t\x12\x0f\n\x07\x65th_dst\x18\x04 \x01(\t\x12\x10\n\x08ip_proto\x18\x05 \x01(\x0c\x12\x0e\n\x06ip_src\x18\x06 \x01(\t\x12\x0e\n\x06ip_dst\x18\x07 \x01(\t\x12\x10\n\x08src_port\x18\x08 \x01(\x05\x12\x10\n\x08\x64st_port\x18\t \x01(\x05*\x1d\n\x06\x41\x63tion\x12\x08\n\x04\x64\x65ny\x10\x00\x12\t\n\x05\x61llow\x10\x01\x62\x06proto3')
)

_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='deny', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='allow', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=332,
  serialized_end=361,
)
_sym_db.RegisterEnumDescriptor(_ACTION)

Action = enum_type_wrapper.EnumTypeWrapper(_ACTION)
deny = 0
allow = 1



_ACLRULES = _descriptor.Descriptor(
  name='AclRules',
  full_name='AclRules',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rules', full_name='AclRules.rules', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=66,
)


_ACLRULE = _descriptor.Descriptor(
  name='AclRule',
  full_name='AclRule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='src_mac', full_name='AclRule.src_mac', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dst_mac', full_name='AclRule.dst_mac', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filter_id', full_name='AclRule.filter_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='AclRule.action', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=155,
)


_TRAFFICFILTER = _descriptor.Descriptor(
  name='TrafficFilter',
  full_name='TrafficFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filter_id', full_name='TrafficFilter.filter_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eth_type', full_name='TrafficFilter.eth_type', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eth_src', full_name='TrafficFilter.eth_src', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eth_dst', full_name='TrafficFilter.eth_dst', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip_proto', full_name='TrafficFilter.ip_proto', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip_src', full_name='TrafficFilter.ip_src', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip_dst', full_name='TrafficFilter.ip_dst', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='src_port', full_name='TrafficFilter.src_port', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dst_port', full_name='TrafficFilter.dst_port', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=330,
)

_ACLRULES.fields_by_name['rules'].message_type = _ACLRULE
_ACLRULE.fields_by_name['action'].enum_type = _ACTION
DESCRIPTOR.message_types_by_name['AclRules'] = _ACLRULES
DESCRIPTOR.message_types_by_name['AclRule'] = _ACLRULE
DESCRIPTOR.message_types_by_name['TrafficFilter'] = _TRAFFICFILTER
DESCRIPTOR.enum_types_by_name['Action'] = _ACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AclRules = _reflection.GeneratedProtocolMessageType('AclRules', (_message.Message,), dict(
  DESCRIPTOR = _ACLRULES,
  __module__ = 'forch.proto.acl_rules_pb2'
  # @@protoc_insertion_point(class_scope:AclRules)
  ))
_sym_db.RegisterMessage(AclRules)

AclRule = _reflection.GeneratedProtocolMessageType('AclRule', (_message.Message,), dict(
  DESCRIPTOR = _ACLRULE,
  __module__ = 'forch.proto.acl_rules_pb2'
  # @@protoc_insertion_point(class_scope:AclRule)
  ))
_sym_db.RegisterMessage(AclRule)

TrafficFilter = _reflection.GeneratedProtocolMessageType('TrafficFilter', (_message.Message,), dict(
  DESCRIPTOR = _TRAFFICFILTER,
  __module__ = 'forch.proto.acl_rules_pb2'
  # @@protoc_insertion_point(class_scope:TrafficFilter)
  ))
_sym_db.RegisterMessage(TrafficFilter)


# @@protoc_insertion_point(module_scope)
