# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: forch/proto/match_rules.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='forch/proto/match_rules.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1d\x66orch/proto/match_rules.proto\"m\n\nMatchRules\x12%\n\x05rules\x18\x01 \x03(\x0b\x32\x16.MatchRules.RulesEntry\x1a\x38\n\nRulesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.MatchRule:\x02\x38\x01\"\xc8\x01\n\tMatchRule\x12\"\n\x08\x65th_type\x18\x01 \x01(\x0e\x32\x10.EthType.EthType\x12\x0f\n\x07\x65th_src\x18\x02 \x01(\t\x12\x0f\n\x07\x65th_dst\x18\x03 \x01(\t\x12\"\n\x08ip_proto\x18\x04 \x01(\x0e\x32\x10.IpProto.IpProto\x12\x0e\n\x06ip_src\x18\x05 \x01(\t\x12\x0e\n\x06ip_dst\x18\x06 \x01(\t\x12\x10\n\x08src_port\x18\x07 \x01(\x05\x12\x10\n\x08\x64st_port\x18\x08 \x01(\x05\x12\r\n\x05\x62idir\x18\t \x01(\x08\"J\n\x07\x45thType\"?\n\x07\x45thType\x12\r\n\tUNDEFINED\x10\x00\x12\x08\n\x04LLDP\x10\x01\x12\x07\n\x03\x41RP\x10\x02\x12\x08\n\x04IPv4\x10\x03\x12\x08\n\x04IPv6\x10\x04\"5\n\x07IpProto\"*\n\x07IpProto\x12\r\n\tUNDEFINED\x10\x00\x12\x07\n\x03TCP\x10\x01\x12\x07\n\x03UDP\x10\x02\x62\x06proto3')
)



_ETHTYPE_ETHTYPE = _descriptor.EnumDescriptor(
  name='EthType',
  full_name='EthType.EthType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LLDP', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ARP', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IPv4', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IPv6', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=358,
  serialized_end=421,
)
_sym_db.RegisterEnumDescriptor(_ETHTYPE_ETHTYPE)

_IPPROTO_IPPROTO = _descriptor.EnumDescriptor(
  name='IpProto',
  full_name='IpProto.IpProto',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TCP', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UDP', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=434,
  serialized_end=476,
)
_sym_db.RegisterEnumDescriptor(_IPPROTO_IPPROTO)


_MATCHRULES_RULESENTRY = _descriptor.Descriptor(
  name='RulesEntry',
  full_name='MatchRules.RulesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='MatchRules.RulesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='MatchRules.RulesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=142,
)

_MATCHRULES = _descriptor.Descriptor(
  name='MatchRules',
  full_name='MatchRules',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rules', full_name='MatchRules.rules', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MATCHRULES_RULESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=142,
)


_MATCHRULE = _descriptor.Descriptor(
  name='MatchRule',
  full_name='MatchRule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='eth_type', full_name='MatchRule.eth_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eth_src', full_name='MatchRule.eth_src', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eth_dst', full_name='MatchRule.eth_dst', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip_proto', full_name='MatchRule.ip_proto', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip_src', full_name='MatchRule.ip_src', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip_dst', full_name='MatchRule.ip_dst', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='src_port', full_name='MatchRule.src_port', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dst_port', full_name='MatchRule.dst_port', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bidir', full_name='MatchRule.bidir', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=345,
)


_ETHTYPE = _descriptor.Descriptor(
  name='EthType',
  full_name='EthType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ETHTYPE_ETHTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=421,
)


_IPPROTO = _descriptor.Descriptor(
  name='IpProto',
  full_name='IpProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _IPPROTO_IPPROTO,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=476,
)

_MATCHRULES_RULESENTRY.fields_by_name['value'].message_type = _MATCHRULE
_MATCHRULES_RULESENTRY.containing_type = _MATCHRULES
_MATCHRULES.fields_by_name['rules'].message_type = _MATCHRULES_RULESENTRY
_MATCHRULE.fields_by_name['eth_type'].enum_type = _ETHTYPE_ETHTYPE
_MATCHRULE.fields_by_name['ip_proto'].enum_type = _IPPROTO_IPPROTO
_ETHTYPE_ETHTYPE.containing_type = _ETHTYPE
_IPPROTO_IPPROTO.containing_type = _IPPROTO
DESCRIPTOR.message_types_by_name['MatchRules'] = _MATCHRULES
DESCRIPTOR.message_types_by_name['MatchRule'] = _MATCHRULE
DESCRIPTOR.message_types_by_name['EthType'] = _ETHTYPE
DESCRIPTOR.message_types_by_name['IpProto'] = _IPPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MatchRules = _reflection.GeneratedProtocolMessageType('MatchRules', (_message.Message,), dict(

  RulesEntry = _reflection.GeneratedProtocolMessageType('RulesEntry', (_message.Message,), dict(
    DESCRIPTOR = _MATCHRULES_RULESENTRY,
    __module__ = 'forch.proto.match_rules_pb2'
    # @@protoc_insertion_point(class_scope:MatchRules.RulesEntry)
    ))
  ,
  DESCRIPTOR = _MATCHRULES,
  __module__ = 'forch.proto.match_rules_pb2'
  # @@protoc_insertion_point(class_scope:MatchRules)
  ))
_sym_db.RegisterMessage(MatchRules)
_sym_db.RegisterMessage(MatchRules.RulesEntry)

MatchRule = _reflection.GeneratedProtocolMessageType('MatchRule', (_message.Message,), dict(
  DESCRIPTOR = _MATCHRULE,
  __module__ = 'forch.proto.match_rules_pb2'
  # @@protoc_insertion_point(class_scope:MatchRule)
  ))
_sym_db.RegisterMessage(MatchRule)

EthType = _reflection.GeneratedProtocolMessageType('EthType', (_message.Message,), dict(
  DESCRIPTOR = _ETHTYPE,
  __module__ = 'forch.proto.match_rules_pb2'
  # @@protoc_insertion_point(class_scope:EthType)
  ))
_sym_db.RegisterMessage(EthType)

IpProto = _reflection.GeneratedProtocolMessageType('IpProto', (_message.Message,), dict(
  DESCRIPTOR = _IPPROTO,
  __module__ = 'forch.proto.match_rules_pb2'
  # @@protoc_insertion_point(class_scope:IpProto)
  ))
_sym_db.RegisterMessage(IpProto)


_MATCHRULES_RULESENTRY._options = None
# @@protoc_insertion_point(module_scope)
