# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: forch/proto/switch_state.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='forch/proto/switch_state.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1e\x66orch/proto/switch_state.proto\"\r\n\x0bSwitchStateb\x06proto3')
)




_SWITCHSTATE = _descriptor.Descriptor(
  name='SwitchState',
  full_name='SwitchState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=47,
)

DESCRIPTOR.message_types_by_name['SwitchState'] = _SWITCHSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SwitchState = _reflection.GeneratedProtocolMessageType('SwitchState', (_message.Message,), dict(
  DESCRIPTOR = _SWITCHSTATE,
  __module__ = 'forch.proto.switch_state_pb2'
  # @@protoc_insertion_point(class_scope:SwitchState)
  ))
_sym_db.RegisterMessage(SwitchState)


# @@protoc_insertion_point(module_scope)
